//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgahiCarDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAgahiCarDetails()
        {
            this.tblCarBodyStatus = new HashSet<tblCarBodyStatus>();
        }
    
        public int AgahiDetailCarID { get; set; }
        public Nullable<int> AgahiID { get; set; }
        public string karkardDaghigh { get; set; }
        public Nullable<int> SaleSakht { get; set; }
        public Nullable<bool> GirboxAuto { get; set; }
        public Nullable<int> SokhtID { get; set; }
        public Nullable<int> RangeKharegiID { get; set; }
        public Nullable<int> RangeDakheliID { get; set; }
        public Nullable<int> CarTipID { get; set; }
        public Nullable<int> MotorHajmID { get; set; }
        public Nullable<int> AirBagNumber { get; set; }
        public Nullable<int> DandehNumber { get; set; }
        public Nullable<bool> SunRoof { get; set; }
        public Nullable<bool> Remote { get; set; }
        public Nullable<bool> SandaliBarghi { get; set; }
        public Nullable<int> SopapID { get; set; }
        public Nullable<decimal> PishPardakht { get; set; }
        public Nullable<decimal> Mahane { get; set; }
        public Nullable<int> ChanMaheID { get; set; }
        public Nullable<decimal> MablagheKole { get; set; }
        public Nullable<int> RokeshTypeID { get; set; }
        public Nullable<int> VamID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> CarConditionID { get; set; }
        public Nullable<int> CarChassisTypeID { get; set; }
        public Nullable<byte> DiffType { get; set; }
        public Nullable<int> CrashTypeID { get; set; }
        public Nullable<int> CarCrashTypeID { get; set; }
        public Nullable<int> CarPelakTypeID { get; set; }
        public Nullable<bool> HasAlarm { get; set; }
        public Nullable<bool> HasSound { get; set; }
    
        public virtual tblAgahi tblAgahi { get; set; }
        public virtual tblAgahiRang tblAgahiRang { get; set; }
        public virtual tblAgahiRang tblAgahiRang1 { get; set; }
        public virtual tblCarMotorHajme tblCarMotorHajme { get; set; }
        public virtual tblCarSokht tblCarSokht { get; set; }
        public virtual tblCarSopapMotor tblCarSopapMotor { get; set; }
        public virtual tblCarTip tblCarTip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCarBodyStatus> tblCarBodyStatus { get; set; }
    }
}
