//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBrands()
        {
            this.tblAgahiCarDetails = new HashSet<tblAgahiCarDetails>();
            this.tblAgahiMobCompDetails = new HashSet<tblAgahiMobCompDetails>();
        }
    
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> ParrentID { get; set; }
        public int BrandTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgahiCarDetails> tblAgahiCarDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgahiMobCompDetails> tblAgahiMobCompDetails { get; set; }
        public virtual tblBrandType tblBrandType { get; set; }
    }
}
