//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarBodyStatus
    {
        public int CarBodyStatusID { get; set; }
        public int AgahiDetailCar { get; set; }
        public Nullable<bool> OneLakeRang { get; set; }
        public Nullable<bool> TwoLakeRang { get; set; }
        public Nullable<bool> ThreeLakeRang { get; set; }
        public Nullable<bool> DorRang { get; set; }
        public Nullable<bool> Chapiye { get; set; }
        public Nullable<bool> ShasiAghab { get; set; }
        public Nullable<bool> ShasiJolo { get; set; }
        public Nullable<bool> KhatoKhash { get; set; }
        public Nullable<bool> KaputRang { get; set; }
        public Nullable<bool> SandoghRang { get; set; }
        public Nullable<bool> SaghfRang { get; set; }
        public Nullable<bool> OtaghTaviz { get; set; }
        public Nullable<bool> NiazBeSafkari { get; set; }
    
        public virtual tblAgahiCarDetails tblAgahiCarDetails { get; set; }
    }
}
