//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsers()
        {
            this.tblUserAgahiStatus = new HashSet<tblUserAgahiStatus>();
            this.tblUserLoginStatus = new HashSet<tblUserLoginStatus>();
            this.tblAgahi = new HashSet<tblAgahi>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Tell { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string SecondryPass { get; set; }
        public string UserLinkPage { get; set; }
        public string PersonelImageUrl { get; set; }
        public string RegisterDate { get; set; }
        public string NationalityID { get; set; }
        public string PostalCode { get; set; }
        public string BussinessFieldID { get; set; }
        public string BirthDate { get; set; }
        public string NickName { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UserTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserAgahiStatus> tblUserAgahiStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLoginStatus> tblUserLoginStatus { get; set; }
        public virtual tblUserType tblUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgahi> tblAgahi { get; set; }
    }
}
