//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAgahiStatus
    {
        public int UserAgahiStatusID { get; set; }
        public Nullable<int> AgahiID { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AgahiStatusID { get; set; }
    
        public virtual tblAgahi tblAgahi { get; set; }
        public virtual tblAgahiStatus tblAgahiStatus { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
