//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGNProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVam
    {
        public int VamID { get; set; }
        public Nullable<decimal> MahanePrice { get; set; }
        public Nullable<int> Teadad { get; set; }
        public string VamDescription { get; set; }
        public Nullable<int> VamYear { get; set; }
        public Nullable<int> AgahiID { get; set; }
    
        public virtual tblAgahi tblAgahi { get; set; }
    }
}
